FROM node:lts-alpine

ENV REACT_APP_BACKEND_URL=http://localhost:8080/

COPY . .

WORKDIR /example-frontend

RUN npm install && \
    npm run build && \
    npm install -g serve && \
    adduser -D frontend && \
    chown -R frontend:frontend /example-frontend

USER frontend

EXPOSE 5000

CMD serve -s -l 5000 build

