FROM golang:1.16
ENV REQUEST_ORIGIN=http://localhost
ADD . .
WORKDIR $GOPATH/example-backend
RUN go build -o server .
RUN useradd -m backend
RUN chown -R backend:backend $GOPATH/example-backend
USER backend
EXPOSE 8080
CMD ["/go/example-backend/server"]

