version: '3.8'

services:
    frontend:
      image: frontend
      build: ml-kurkkumopo-frontend
      ports:
        - 3000:3000
      container_name: example-frontend
    backend:
      image: backend
      build: ml-kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
      container_name: example-backend        
    training:
      image: training
      build: ml-kurkkumopo-training
      volumes:
        - model:/src/model
        - imgs:/src/imgs
      container_name: example-training


volumes:
  imgs:
  model:

